spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/app
    username: app
    password: app
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false

  jackson:
    serialization:
      indent_output: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info, mappings

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.boot.autoconfigure.web: DEBUG